use_frameworks!

platform :ios, '9.0'

target 'YYNetWork_Example' do
  pod 'AFNetworking'
  pod 'Define',:git => 'https://github.com/MasterYong/Define.git'
  pod 'YYNetWork',: path => '../'
  target 'YYNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
