use_frameworks!

platform :ios, '8.0'

target 'YYNetWork_Example' do
  pod 'YYNetWork', :path => '../'

  target 'YYNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
